[package]
name = "starknet-message"
version = "1.0.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
router-api = { workspace = true }
starknet-checked-felt = { workspace = true }
starknet-crypto = { workspace = true }
starknet-types-core = { workspace = true }
error-stack = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
