[package]
name = "evm-gateway"
version = "1.0.0"
rust-version = { workspace = true }
edition = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axelar-wasm-std = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
ethers-contract = { workspace = true }
ethers-core = { workspace = true }
k256 = { workspace = true }
multisig = { workspace = true }
router-api = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }

ethers = { version = "2.0.14", optional = true }

[lints]
workspace = true

[features]
external-dep = ["ethers"]
