[package]
name = "aleo-string-encoder"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
serde-aleo = { workspace = true }

[lints]
workspace = true
