[package]
name = "aleo-utils-temp"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
arbtest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
snarkvm-cosmwasm = { workspace = true, features = ["program", "network"]}
nom = "8.0.0"
