[package]
name = "aleo-gateway"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
aleo-types = { workspace = true }
aleo-string-encoder = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
interchain-token-service = { workspace = true }
hex = { workspace = true }
multisig = { workspace = true, features = ["library"] }
router-api = { workspace = true }
serde = { version = "1.0.147", features = ["derive"] }
serde_with = "3.12.0"
snarkvm-cosmwasm = { workspace = true, features = ["cosmwasm"] }
thiserror = { workspace = true }

[dev-dependencies]
rand = "0.8"
axelar-wasm-std = { workspace = true }
sha3 = { workspace = true }

[lints]
workspace = true
