[package]
name = "aleo-gateway"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
aleo-types = { workspace = true }
router-api = { workspace = true }
error-stack = { workspace = true }
thiserror = { workspace = true }
bitvec = { workspace = true }

[lints]
workspace = true
