[package]
name = "aleo-gateway"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
aleo-types = { workspace = true }
aleo-utils = { workspace = true }
router-api = { workspace = true }
error-stack = { workspace = true }
thiserror = { workspace = true }
cosmwasm-std = { workspace = true }
hex = { workspace = true }
multisig = { workspace = true, features = ["library"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_with = "3.12.0"
snarkvm-cosmwasm = { workspace = true, features = ["program", "network"]}

[dev-dependencies]
rand = "0.8"

[lints]
workspace = true
