[package]
name = "aleo-gateway"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
aleo-types = { workspace = true }
router-api = { workspace = true }
error-stack = { workspace = true }
thiserror = { workspace = true }
cosmwasm-std = { workspace = true }
hex.workspace = true
multisig = { workspace = true, features = ["library"] }
snarkvm-cosmwasm = { workspace = true }

[dev-dependencies]
# snarkos-account = { version = "3.1.0" }
# snarkvm = { version = "1.1.0" }
rand = "0.8"

[lints]
workspace = true
