[package]
name = "aleo-types"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
axelar-wasm-std = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
bech32 = { workspace = true }
snarkvm-cosmwasm = { workspace = true, features = ["console"] }

[dev-dependencies]
axelar-wasm-std = { workspace = true }
assert_ok = { workspace = true }

[lints]
workspace = true
