[package]
name = "aleo-types"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
axelar-wasm-std = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
bech32 = { workspace = true }
hex = { workspace = true }
lazy_static = "1.4.0"

[dev-dependencies]
axelar-wasm-std = { workspace = true }
assert_ok = { workspace = true }
aleo-utils = { workspace = true }

[lints]
workspace = true
