health_check_bind_addr="0.0.0.0:3000"
tm_jsonrpc="http://devnet-amplifier.axelar.dev:26657"
tm_grpc="tcp://devnet-amplifier.axelar.dev:9090"
event_buffer_cap=10000

[service_registry]
# this is the Service registry contract address, deployed and maintained by Axelar
cosmwasm_contract="axelar1g5vu3hs8g5hq3wy7q2p4c6q0aar08f3n2z73nrxgf56rg7yrzkds5kh89l"

[broadcast]
batch_gas_limit="10000000"
broadcast_interval="1s"
chain_id="devnet-amplifier"
gas_adjustment="2"
gas_price="0.00005uamplifier"
queue_cap="1000"
tx_fetch_interval="600ms"
tx_fetch_max_retries="10"

[tofnd_config]
key_uid="axelar"
party_uid="ampd"
url="http://127.0.0.1:50051"

[[handlers]]
# this is the Multisig contract address, deployed and maintained by Axelar
# cosmwasm_contract = "axelar19jxy26z0qnnspa45y5nru0l5rmy9d637z5km2ndjxthfxf5qaswst9290r"
# this is Aleo Multisig needed to add the schnorr signature
cosmwasm_contract = "axelar19gzem44q7kl9zwdt3r0vnmaafgj6j63ke80ca0x38crzchj593wsty08es"

type = "MultisigSigner"

# [[handlers]]
# type = 'SuiMsgVerifier'
# cosmwasm_contract = 'axelar1hmdc9verjjfttcsav57nhcjm7hfcrpg08tqk9phcceulzurnfqns9yqsap'
# rpc_url = "https://fullnode.testnet.sui.io:443"
#
# [[handlers]]
# type = 'SuiVerifierSetVerifier'
# cosmwasm_contract = 'axelar1hmdc9verjjfttcsav57nhcjm7hfcrpg08tqk9phcceulzurnfqns9yqsap'
# rpc_url = "https://fullnode.testnet.sui.io:443"
#
# [[handlers]]
# type = 'EvmMsgVerifier'
# cosmwasm_contract = 'axelar14lh98gp06zdqh5r9qj3874hdmfzs4sh5tkfzg3cyty4xeqsufdjqedt3q8'
# chain_name = 'avalanche'
# chain_rpc_url = "https://api.avax-test.network/ext/bc/C/rpc"
#
#
# [[handlers]]
# type = 'EvmVerifierSetVerifier'
# cosmwasm_contract = 'axelar14lh98gp06zdqh5r9qj3874hdmfzs4sh5tkfzg3cyty4xeqsufdjqedt3q8'
# chain_name = 'avalanche'
# chain_rpc_url = "https://api.avax-test.network/ext/bc/C/rpc"

# voting-verifier
# cosmwasm_contract = 'axelar19r4wxttfjtyenmqvm220nfjwckya0xaqzs7s3zwuk06vkry9vntql4cd4d'
# gateway contract
# cosmwasm_contract = 'axelar1a9d3a3hcykzfa8rn3y7d47ns55x3wdlykchydd8x3f95dtz9qh0q3vnrg0'

[[handlers]]
type = 'AleoMsgVerifier'
# voting-verifier contract
cosmwasm_contract = "axelar1gneuvdsf733h77hj6hn24kukgljvr5xnlladxnnc9gqqwwvu3uvsnxl2hc"
chain_name = 'aleo-2'
chain_rpc_url = "http://localhost:3030"
base_url = "http://localhost:3030"
network = "testnet"
gateway_contract = "vzevxifdoj.aleo"
# cosmwasm_contract = "axelar1gneuvdsf733h77hj6hn24kukgljvr5xnlladxnnc9gqqwwvu3uvsnxl2hc"


# [[handlers]]
# type = 'AleoVerifierSetVerifier'
# cosmwasm_contract = 'axelar19r4wxttfjtyenmqvm220nfjwckya0xaqzs7s3zwuk06vkry9vntql4cd4d'
# chain_name = 'aleo'
