[package]
name = "axelar-wasm-addresses"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
aleo-types = { workspace = true }
alloy-primitives = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
starknet-checked-felt = { workspace = true }
stellar-xdr = { workspace = true }
sui-types = { workspace = true }
thiserror = { workspace = true }
valuable = { version = "0.1.0", features = ["derive"] }

[dev-dependencies]
assert_ok = { workspace = true }
cw-multi-test = { workspace = true }
axelar-wasm-std = { workspace = true }

[lints]
workspace = true
